services:
  flask_app:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: flask_app:latest
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      SECRET_NAME: flask-app-secret
      AWS_REGION: us-east-1
      DB_USER: postgres
      DB_HOST: my-postgress-db.cc3m62swkfac.us-east-1.rds.amazonaws.com
      DB_NAME: flask
      DB_PORT: 5432
      S3_BUCKET: my-second-hand-clothes-storage
      SECRET_KEY: dev_secret_key
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

