apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.flask.replicas }}
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: flask-app
          image: {{ .Values.flask.image }}
          ports:
            - containerPort: {{ .Values.flask.containerPort }}
          env:
            - name: DB_USER
              value: "postgres"
            - name: DB_HOST
              value: "my-postgress-db.cc3m62swkfac.us-east-1.rds.amazonaws.com"
            - name: DB_NAME
              value: "flask"
            - name: DB_PORT
              value: "5432"
            - name: AWS_REGION
              value: "{{ .Values.aws.region }}"
            - name: SECRET_KEY
              value: "{{ .Values.flask.secretKey }}"