namespace: dev
serviceAccountName: flask-app-sa
flask:
  image: noa10203040/flask_app:90476060
  replicas: 1
  containerPort: 5000
  servicePort: 80
  secretKey: dev_secret_key
aws:
  region: us-east-1
