namespace: staging
serviceAccountName: flask-app-sa
flask:
  image: noa10203040/flask_app:7c742dba
  replicas: 1
  containerPort: 5000
  servicePort: 80
  secretKey: staging_secret_key
aws:
  region: us-east-1
